language: python

python:
  - "3.7"

install:
  - cd django_team_websites/
  - pip install pylint
  - pip install -r requirements.txt

script:
  - pylint --disable=R0401 lab_website/*py
  - python manage.py test

notifications:
  email:
    on_success: never
    on_failure: always
