language: python

python:
  - "3.7"

install:
  - cd django_team_websites/
  - pip install -r requirements.txt

script:
  - python manage.py test

notifications:
  email:
    on_success: never
    on_failure: always
