# Generated by Django 2.2.5 on 2019-11-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('position', models.CharField(max_length=36)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_website.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('volume', models.PositiveSmallIntegerField()),
                ('affiliation', models.CharField(max_length=100)),
                ('doi', models.CharField(max_length=100)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_website.Person')),
            ],
        ),
    ]
