# Generated by Django 2.2.5 on 2019-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0002_auto_20191124_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='about_us',
            field=models.TextField(null=True),
        ),
    ]
