# Generated by Django 2.2.5 on 2019-11-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0003_lab_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaseachField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_website.Lab')),
                ('people', models.ManyToManyField(to='lab_website.Person')),
            ],
        ),
    ]
