# Generated by Django 2.2.5 on 2019-11-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0004_reaseachfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReaseachField',
            new_name='ResearchField',
        ),
    ]
