# Generated by Django 2.2.5 on 2019-11-24 17:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0005_auto_20191124_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='person',
            name='room',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_website.Lab')),
            ],
        ),
    ]
