# Generated by Django 2.2.5 on 2019-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0006_auto_20191124_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(default='Journal of Applied Science', max_length=200),
            preserve_default=False,
        ),
    ]
