# Generated by Django 2.2.5 on 2019-11-24 19:53

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0007_publication_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='name_url',
            field=models.CharField(default='insane-lab', max_length=36, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
            preserve_default=False,
        ),
    ]
