# Generated by Django 2.2.5 on 2019-11-24 21:49

import django.core.validators
from django.db import migrations, models
import lab_website.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0010_auto_20191124_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='name_url',
            field=models.CharField(max_length=36, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), lab_website.validators.validate_unique_lab_name_url]),
        ),
    ]
