# Generated by Django 2.2.5 on 2019-11-24 21:56

from django.db import migrations, models
import lab_website.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0011_auto_20191124_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=36, validators=[lab_website.validators.validate_unique_lab_name]),
        ),
    ]
