name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd django_team_websites
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --disable=R0401 django_team_websites/lab_website/*py
    - name: Run app tests
      run: | 
        cd django_team_websites
        python manage.py test
